# -*- coding: utf-8 -*-
"""bf%-model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rYnm4TnFjd_KCP1IZP9btLn3ATk7bIyK

Data Preparation
"""

import pandas as pd
import torch
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#load data
df = pd.read_csv('BodyFat - Extended.csv')

if df['Height'].mean() < 3.0:
    print("⚠️ Detected Height in Meters (e.g., 1.72). Converting to Cm (e.g., 172)...")
    df['Height'] = df['Height'] * 100

# binary encode the gender
df['Sex'] = df['Sex'].map({'M': 0, 'F': 1})

#remove people with less than 2% bodyfat and more than 60% bodyfat (likely outliers)
df = df[(df['BodyFat'] > 2) & (df['BodyFat'] < 60)]

#add bmi feature/column to improve model accuracy
df['BMI'] = df['Weight'] / ((df['Height'] / 100) ** 2)
print(f"Average BMI calculated: {df['BMI'].mean():.2f}")

#define features and targets
# remove these 3 column, set up errors to ignore if not find
X = df.drop(['BodyFat', 'Original', 'Density'], errors='ignore', axis=1).values
y = df['BodyFat'].values
# note : .values turns the df into numpy array

#split the data for train test (80:20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=67)

# Neural Networks are bad at math if the numbers are vastly different sizes.
# if weight in lb and height in m will think Weight is 100x more important just because the number is bigger
# StandardScaler forces all data to have an average (mean) of 0 and a variance of 1. It puts everything on a level playing field.
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
# why fit.transfrom for train but only transform for test
# .fit_transform on your training data to learn and apply the scaling parameters, but only use .transform on your test data to ensure
# the model scales new information using only what it learned from the training set, preventing "data leakage" (cheating).

#convert to data (tensors) for pytorch
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.FloatTensor(y_train).view(-1, 1) #the reason of this view command is to change the flat one line numpy
y_test = torch.FloatTensor(y_test).view(-1, 1)   #array to a vertical(column) structure to align our train data

print("✅ Data Ready!")
print(f"Inputs per person: {X_train.shape[1]}") # Should be 14

"""NN Architecture Development"""

import torch.nn as nn

class BodyFatModel(nn.Module): #inherits from torch
    def __init__(self, input_features):
       super().__init__()

       #first layer
       self.fc1 = nn.Linear(input_features, 128) #from 14 neurons(inputs) to 128 neurons
       self.act1 = nn.ReLU() #activation function
       self.drop1 = nn.Dropout(0.2) #randomly forgetting 20% of the data to prevent overfitting

       #second layer
       self.fc2 = nn.Linear(128, 64) #from 128 neurons to 64 neurons
       self.act2 = nn.ReLU() #activation function
       self.drop2 = nn.Dropout(0.1) #randomly forgetting 10% of the data to prevent overfitting

       #third layer/output
       self.out = nn.Linear(64, 1) #from 64 neurons to 1 neurons (our bf% output)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act1(x)
        x = self.drop1(x)
        x = self.fc2(x)
        x = self.act2(x)
        x = self.drop2(x)
        return self.out(x)

#this is to dynamically adjust the number of feature in our model
input_count = X_train.shape[1]
model = BodyFatModel(input_count)
print("✅ Brain Created!")

"""Training NN"""

import torch.optim as optim

#loss function, we use Mean Square Error
criterion = nn.MSELoss()
#optimizer to change the weight and biases of the NN
optimizer = optim.Adam(model.parameters(), lr=0.001)

#setup Training loop
epochs = 5000
print("Starting Training")

for i in range(epochs):

  y_pred = model(X_train) #feed training data to model
  loss = criterion(y_pred, y_train) #calculate loss

  optimizer.zero_grad() #clean the math from previous loops
  loss.backward() #backpropagation calculation
  optimizer.step() # acts on the calculated change from backpropagation

  if i % 200 == 0:
    print(f'Epoch {i}, Loss={loss.item()}')

print("✅ Training Complete!")

"""Testing NN"""

model.eval() #this is like changing mode from learning to testing i think

with torch.no_grad():# this line says forget all the backpropagation calculation stuff, only predicts
    y_eval = model(X_test) #feed test data
    test_loss = criterion(y_eval, y_test) #calculate loss

print(f"\nFinal Test Error score: {test_loss.item():.4f}")
print("-" * 30)
print("REAL VS PREDICTED (First 5 People)")
print("-" * 30)

#print first 5 entries
for i in range(50):
    real = y_test[i].item()
    pred = y_eval[i].item()
    diff = abs(real - pred)
    print(f"Real: {real:.1f}%  |  AI Guessed: {pred:.1f}%  (Diff: {diff:.1f}%)")

"""Download Model"""

import joblib
torch.save(model.state_dict(), 'naksihat_bf%_model.pth')
joblib.dump(scaler, 'scaler.pkl')
print("✅ Files saved!")